### PR TITLE
Fix PyPI URL

### PR DESCRIPTION
**Pull request by adamchainz**
😱

### CODE REVIEW

**Comment by rixx** [comment]
Should be redirecting, though. Isn't it?

Thanks anyways!

**Comment by adamchainz** [comment]
Doesn't for me - https://github.com/rixx/django_context_decorator

**Comment by rixx** [comment]
Weeeird, it does for me.

```shell
$ http "https://github.com/rixx/django_context_decorator"

HTTP/1.1 301 Moved Permanently
Cache-Control: no-cache
…
Content-Type: text/html; charset=utf-8
Date: Sun, 14 Apr 2019 14:37:50 GMT
Location: https://github.com/rixx/django-context-decorator
Status: 301 Moved Permanently

<html><body>You are being <a href="https://github.com/rixx/django-context-decorator">redirected</a>.</body></html>
```
```

**Comment by adamchainz** [comment]
Very weird, it does for me checking on a different internet connection!

**Pull request merged**
